#!/bin/bash
# Process with Makefile

#Copyright (C) 2013 Robin McCorkell

#This file is part of Karoshi Client.
#
#Karoshi Client is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Karoshi Client is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Karoshi Client.  If not, see <http://www.gnu.org/licenses/>.

set -e

[[ -d "@localstatedir@/lib/karoshi/firefox" ]]

#Copy domain CA certificate
if [[ -f "@localstatedir@/lib/karoshi/firefox/cacert.pem" ]]; then
	rm -f "@localstatedir@/lib/karoshi/firefox/cacert.pem"
fi
if [[ -f /tmp/netlogon/domain_information/cacert.pem ]]; then
	cp /tmp/netlogon/domain_information/cacert.pem "@localstatedir@/lib/karoshi/firefox/"
fi
